services:
  # Frontend Next.js App
  - type: web
    name: solana-jackpot-frontend
    runtime: node
    env: node
    plan: starter
    rootDir: .
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SOCKET_URL
        value: https://solana-jackpot-api.onrender.com
      - key: NEXT_PUBLIC_SOLANA_NETWORK
        value: mainnet-beta
      - key: NEXT_PUBLIC_RPC_ENDPOINT
        value: https://magical-boldest-patina.solana-mainnet.quiknode.pro/a94255dcbb27e52b1d4cca35d10e899b82b6bdba/

  # Backend API Server
  - type: web
    name: solana-jackpot-api
    runtime: node
    env: node
    plan: starter
    rootDir: server
    buildCommand: npm install --legacy-peer-deps
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 